-- Create database CodenationStudyBD

--USE CodenationStudyBD
--GO

CREATE TABLE Profissao
(
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Descricao VARCHAR(100) NOT NULL
);

CREATE TABLE Esposa 
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	DataNasc SMALLDATETIME,
	IdProfissao INT,
	FOREIGN KEY (IdProfissao) REFERENCES Profissao(Id)
);

CREATE TABLE Marido(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	DataNasc SMALLDATETIME ,
	IdProfissao INT,
	IdEsposa INT NOT NULL,
	FOREIGN KEY (IdProfissao) REFERENCES Profissao(Id),
	FOREIGN KEY (IdEsposa) REFERENCES Esposa(Id)
);
CREATE TABLE Pai (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL
);

CREATE TABLE Filho (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	IdPai INT NOT NULL,
	FOREIGN KEY (IdPai) REFERENCES Pai(Id),
);

CREATE TABLE Tia(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL
);

CREATE TABLE Sobrinho(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL
);

CREATE TABLE TiaSobrinho (
	IdTia INT,
	IdSobrinho INT,
	FOREIGN KEY (IdTia) REFERENCES Tia(Id),
	FOREIGN KEY (IdSobrinho) REFERENCES Sobrinho(Id)
);
